reporter/datadog_reporter.go
reporter/symbol_uploader.go

Use basename to report mappings / function names. This matches what is done in `otel-profiling-agent`.

[PROF-10607] Use basename instead of full path

---

Dockerfile

Remove golangci install script and replace it with `go install ...`
Make code scanning happy.

Remove golangci install script usage

---

.github/workflows/codeql-analysis.yml
.github/workflows/label.yml
.github/workflows/pre-release.yaml

Currently, we receive two successive events when dependabot opens a PR, first an `opened` event, then a `labeled` events, since dependabot always adds the `dependencies` label.
However, the second event cancels the first workflow, since it is part of the same concurrency group. Since the second event is a `labeled` event that isn't about the `publish-dev-test` label, tests are not re-ran in the second workflow. The PR stays stuck waiting for status checks for build and test, and those check will never complete.
We fix this by extracting the "run on publish-dev-test" logic to a separate workflow that calls the pre-release workflow. By creating a separate workflow, this will not impact status checks, since labeled actions will live in a separate namespace under "Labeled / ".
(Thanks to …

github: run workflows for dependabot

---

.github/workflows/build.yml

Add `pull-request: write` permission to lint job.
`pull-request: write` is required to add comments to the PR.

Fix lint job permissions

---

Dockerfile
LICENSE-3rdparty.csv
Makefile
README.md
cli_flags.go
doc/running-in-docker.md
doc/running-in-kubernetes.md
doc/running-on-host.md
docker-compose.yml
go.mod
go.sum
helpers.go
main.go
reporter/config.go
reporter/datadog_reporter.go
reporter/datadog_upload.go
reporter/symbol_uploader.go

Rename env variables used for configuration to be consistent with other Datadog profilers (eg `DD_SERVICE`, `DD_PROFILING_UPLOAD_PERIOD`).
Also add a prefixed version of these variables (eg `DD_HOST_SERVICE`, `DD_HOST_PROFILING_UPLOAD_PERIOD`) that takes precedence over the non-prefixed version for cases where host profiler might be running along side another runtime profiler and a different configuration is needed for the host profiler.

Rename env variables to follow DataDog profiling naming conventions

---

README.md

Update documentation for development setup
N/A
N/A
Tested locally.

documentation: update README for development setup

---

containermetadata/containermetadata.go
containermetadata/containermetadata_test.go
containermetadata/testdata/cgroupv1systemd

The existing default pattern would match systemd service names which only contain letter a-f (see added test which fails with the current code).
This commit extracts the container regex pattern used by the datadog-agent, and uses it as a default pattern.
This makes the pattern more restrictive, avoiding the addition of an incorrect container_id tags for some systemd services.
Profiles contained an incorrect container id, with the example added in the test. 
N/A
Added tests, and tested locally in the workspace.

containermetadata: make default pattern more restrictive

---

Dockerfile

Move the go install command so that it's called by the build user instead of root.
Running go install with root would lead to some folders in /go/pkg/ being owned by root and not writable by the build user, which eventually leads to permission errors when building the profiler, specifically to download new dependencies.
Also put /go in a volume which is persisted between consecutive runs, meaning docker-compose restart will reuse the go cache / go dependencies speeding up builds for local development.
Speed up local builds, fix permissions for `/go` directory.
N/A
Tested locally with:
```
docker-compose build
docker-compose up -d --force-recreate
docker-compose restart
```
And verifying that all commands work, containers are started as expected, and during restart go dependencies are not …

dockerfile: remove gopath override

---

containermetadata/containermetadata.go

Fix container metadata detection
A regression in https://github.com/DataDog/dd-otel-host-profiler/pull/40 broke container id detection
N/A
Tested locally

containermetadata: fix cgroup pattern

---

cli_flags.go
helpers.go
main.go
version/version.go

Service version was incorrectly being used for the profiler version when uploading symbols.
This change removes service version as it was not used anywhere else and use profiler version instead.
It also removes the "v" prefix from the profiler version.

fix: Use correct profiler version for symbol upload

---

README.md

Update readme.
Deprecating the old repository: https://github.com/DataDog/otel-profiling-agent, and switching development to the new repository.
N/A
N/A

README.md: remove experimental notice

---

containermetadata/containermetadata.go
containermetadata/containermetadata_test.go

Use full pod name for container metadata
Previously, the logic would truncate the replicaset and pod hash from the pod name, showing the deployment name instead. this doesn't let users easily distinguish between two pods from the same replicaset running on the same node.
N/A
N/A

containermetadata: use full pod name

---

Dockerfile
README.md
go.mod

Bumps go to version 1.23.6.
It is generally good practice to stay as up-to-date as possible on go releases.
We could not bump to the latest version (1.24.0) because the corresponding Docker image is not yet available.
Simply check that the project still builds and that there is no regression. You can do that by using `make` and `make test`. You can also check that the project builds successfully in the docker image by running `make profiler-in-docker`.

Bump go version to 1.23.6

---

Makefile
cli_flags.go
go.mod
go.sum
main.go

1. Enables the use of the debug eBPF build by default.
2. Enables debug tracing through --verbose-ebpf, which also enables redirection of logs from trace_pipe to the log output.
It makes debugging require less configuration.
None.
Check that, when invoked with --verbose-ebpf, the profiler outputs ebpf logs.
Check that when invoked without that flag, nothing changes.

Enable debug tracing

---

go.mod
go.sum

Make opentelemetry-ebpf-profiler version point on datadog branch

fix: Make opentelemetry-ebpf-profiler version point on datadog branch

---

LICENSE-3rdparty.csv
cli_flags.go
go.mod
go.sum
main.go
reporter/config.go
reporter/datadog_reporter.go
reporter/pipeline/pipeline.go
reporter/pipeline/pipeline_test.go
reporter/symbol/elf.go
reporter/symbol_querier.go
reporter/symbol_query_batching.go
reporter/symbol_query_batching_test.go
reporter/symbol_uploader.go
reporter/symbol_uploader_test.go

Batch requests to symbol-query API endpoint.
Avoid being rate limited by endpoint.
This change introduces `BatchSymbolQuerier` which implements a `QuerySymbols` method that blocks until the request is completed.
`QuerySymbols` pushes query into a synchronous channel and then waits on a `done` channel . Internally `BatchSymbolQuerier` has a single worker goroutine that fetches queries from channel and stores them in an array. Batch call is done at regular time intervals.
Also fixes symbol upload for vdso: vdso does not have a file associated to it (its path is empty), hence we need to dump its content to disk to be able to upload it.

[PROF-11308] feat: Batch requests to symbol-query API endpoint

---

go.mod
go.sum

Uses an updated version of the ebpf profiler which can profile nodejs v16.0.0+ programs on arm64.
Run a nodejs program on an arm64 machine and observe the profile. You could compare it to the same program being profiled on amd64 for reference.

enable nodejs profiling on arm64

---

reporter/symbol/elf_wrapper.go

Always load ELF sections
Missing ELF sections would lead to `debug_info` not being detected.
N/A
N/A

uploader: always load ELF sections

---

go.mod
reporter/symbol_uploader.go

Make symbol uploads to different endpoints concurrent.
A lot of the work done for symbol upload was redundant (creation of symbol file, creation and compression of the request).
This PR makes sure that symbol file creation and building of request body is done once, and then fan out the upload part.

Concurrent symbol upload

---

reporter/pipeline/pipeline.go
reporter/pipeline/pipeline_test.go

Fix flaky batching stage test:
* Ensure there is only one timer active at a time
* Ensure the timer has been reset (by blocking for waiters) before advancing the fake clock

Fix flaky batching stage test

---

pclntab/pclntab.go
reporter/symbol_uploader.go
reporter/symbol_uploader_test.go

Add various test cases for symbol uploader.
Fix wrong symbol source when uploading Go binary with an error during pclntab extraction.

Add symbol uploader tests

---

main.go

We were not checking whether DD_SITE, DD_API_KEY and DD_APP_KEY were already present in the list of additional endpoints.
Therefore, if by mistake DD_SITE (along with APP/API keys) are exactly the same as a site added in DD_HOST_PROFILING_ADDITIONAL_SYMBOL_ENDPOINTS,  profiles and symbols would be sent twice to the agent.

fix: ensure sites are not duplicated

---

.github/workflows/build.yml
.golangci.yml
Dockerfile
Makefile
containermetadata/container.go
containermetadata/containermetadata.go
containermetadata/containermetadata_test.go
go.mod
pclntab/pclntab_test.go
reporter/pipeline/pipeline_test.go
reporter/symbol/elf.go
reporter/symbol/elf_wrapper.go
reporter/symbol/source.go
reporter/symbol_query_batching_test.go
reporter/symbol_uploader.go
reporter/symbol_uploader_test.go

* Bump Go version to 1.24.2 to fix [GO-2025-3563](https://github.com/DataDog/dd-otel-host-profiler/actions/runs/14836064238/job/41647509934)
* Bump golangci version and use https://github.com/golangci/golangci-lint-action instead of https://github.com/reviewdog/action-golangci-lint

chore: bump Go version to 1.24.2

---

reporter/datadog_reporter.go

When a container starts, the initial process is runc which then execs into the final binary with the container environment.
This change improves DD_SERVICE detection by:
* First checking if DD_SERVICE is set in the trace metadata
* If not set and executable path differs from trace path (indicating exec), reading DD_SERVICE from process environment# 
Also emit `service_inferred:no` tag even when service is not inferred.

fix: improve DD_SERVICE detection for containerized processes

---

reporter/datadog_reporter.go

Stop marking system as an inferred service.
system represents threads that are launched by the kernel, there is no way to set a DD_SERVICE environment variable for these threads, as such we should not mark them as inferred (which would cause the tooltip that suggests to set DD_SERVICE to appear).
The tooltip we'd like to avoid showing:
N/A

reporter: system is not an inferred service

---

go.mod
go.sum

- Generated the version by following https://github.com/DataDog/dd-otel-host-profiler/blob/e9bead8260239cb5090d5f1d0835fbc96af6e6fe/go.mod#L128
- Bump our fork of opentelemetry-ebpf-profiler to include these changes (https://github.com/DataDog/opentelemetry-ebpf-profiler/pull/20)
Address https://github.com/DataDog/dd-otel-host-profiler/issues/168
N/A
Tested on workspace environment, produced reasonable profiles and flamegraphs. Don't have a node.js / nsolid setup, but would test on that if we did. Should work identically to upstream though, and those changes are mostly a regex change so don't expect that it behave strangely.

[PROF-12186] Bump opentelemetry-ebpf-profiler to include nsolid fix

---

.github/workflows/build.yml

* Remove coverprofile option because it disables test caching (https://github.com/golang/go/issues/23565).
* Merge build and test jobs so that they can both benefit from the cache (otherwise they would use the same cache key, but only one of them would be able to save its output to the cache).

ci: improve test caching

---

reporter/symbol/elf_wrapper.go

`.debug_frame` section does not appear to be present in separate debug infos.

bugfix: Do not look for .debug_frame in separate debug files

---

reporter/symbol/elf_wrapper.go

In symbol uploader, when we have a filepath, we use `pelf.Open` to re-open the file instead of using the previously created `ReaderAtCloser`. This is to benefit from mmap when reading the file.

perf: Use mmap in symbol uploader

---

reporter/datadog_reporter.go

Trim ` (deleted)` suffix from executable path
if the file was deleted, the path we get might contain a (deleted) suffix which can be confusing for users, as we'd show it both in:
- the service name (will be foo_deleted)
- the root frame (will be foo (deleted))
this commit strips the (deleted) suffix from the executable path
Tested locally as seen above.

fix(reporter): trim (deleted) suffix from executable path

---

reporter/pprof/profile_builder.go

in case we encounter unsymbolized kernel frames, this allows showing "UNKNOWN"
otherwise, the backend will show "Unknown Function (DUMMY)" which can be confusing for users
Before:
After:
N/A
Tested locally per screenshots above

fix(reporter): set function name to UNKNOWN when empty

---

docker/dev/Dockerfile
docker/dev/entrypoint.sh
go.mod

Update go version to 1.24.6
Fix check for already mounted debugfs (needs to be done with root).

Update go version to 1.24.6

---

.gitlab-ci.yml

Images repository CI pipeline has been fixed to avoid running dynamic build / mirroring jobs when triggered from this repository.

chore: remove workaround for gitlab

---

reporter/pprof/profile_builder.go

Instead of adding a Line with an empty Function, we now emit no Line objects for native frames.
Allow simpler and more consistent code on backend side.

fix: do not emit Lines for native frames

---

reporter/datadog_reporter.go
reporter/datadog_reporter_test.go
reporter/symbol_uploader_test.go

The local file naming needs to consider service name and containers. With split by service, we were only keeping the last profile being reported. I also added a simple counter to avoid future collisions.
Enable local tests
Enable prof-correctness tests
NA
Here is my command line
```
sudo DD_HOST_PROFILING_SERVICE=r1-laptop ./dd-otel-host-profiler --upload-period=5s --split-by-service=true --pprof-prefix=$PWD/temp/pprof
```
Which shows following split

Local profile reporting - Adjust the file naming
